name: Stratego
version: '${project.version}'
main: me.tim.stratego.Stratego
api-version: '1.20'
commands:
  blue:
    usage: /blue <Player>
  red:
    usage: /red <Player>
  showteams:
    usage: /showteams
  availablecards:
    usage: /availablecards
  gamestate:
    usage: /gamestate <gamestate>
